[language-server.fsharp-lsp]
command = "fsautocomplete"
config = { AutomaticWorkspaceInit = true }

[language-server.fsharp-lsp.config]
AutomaticWorkspaceInit = true

[language-server.texlab.config.texlab.build]
onSave = true

[language-server.texlab.config.texlab.inlayHints]
labelDefinitions = true
labelReferences = true

[[language]]
name = "fsharp"
scope = "source.fs"
roots = ["sln", "fsproj"]
injection-regex = "fsharp"
file-types = ["fs", "fsx"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
auto-format = true
language-servers = [ "fsharp-lsp" ]

[[grammar]]
name = "fsharp"
source = { git = "https://github.com/kaashyapan/tree-sitter-fsharp", rev = "18da392fd9bd5e79f357abcce13f61f3a15e3951" }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "rust"

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"

[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

# If this doesn't work, you might be on a older release version which handles this differently.
# Try using [language.config.check] instead of [language-server.rust-analyzer.config.check]
[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
autoreload = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

[[language]]
name = "haskell"
auto-format = true
indent = { unit = "  ", tab-width=2 }

